POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "description": "hi man",
    "date": "2023-11-02",
    "specialist": "nothing",
    "type": "HealthCheck",
    "healthCheckRating": 0
}

